# Site
name: 'd5a10'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
#disqus: 'demowebsite'
email: 'd5a10.editora@gmail.com'
mailchimp-list: 'https://gmail.us4.list-manage.com/subscribe/post?u=2e2de7e803c19c65957be170e&amp;id=436c8b7690'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Naira:
      name:           Naira Passoni
      site:           https://www.linkedin.com/in/naira-passoni-6756bb101/
      avatar:         assets/images/naira.jfif
      bio:            "Mãe, jornalista, autora, produtora de conteúdo... Em busca de respostas para as dúvidas da maternidade e da vida profissional. Aqui, quero dividir com outras pessoas as experiências e expectativas dessa jornada incrível e complexa! 😉"
      email:          naira.aprender.digital@gmail.com
      twitter:        https://twitter.com/NairaPassoni

    Parau:
      name:           Parahuari Branco (Parau)
      site:           https://www.linkedin.com/in/parau/
      avatar:         assets/images/parau.jfif
      bio:            "Pai, educador e desenvolvedor. Apaixonado pela área de educação, tenho mais de 20 anos de experiência no desenvolvimento de soluções tecnológicas voltadas a aprendizagem. Aqui, escrevo sobre o mundo digital e o relacionamento saudável entre a criança e a tecnologia."
      email:          d5a10.editora@gmail.com
      twitter:        https://twitter.com/parau
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Naira
      avatar: /assets/images/naira.jfif
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]