# Site
name: 'd5a10'
description: 'd5a10 é seu novo canal de informação sobre uma fase interessante e desafiadora para os pais, que compreende a idade de 5 a 10 anos! Aqui, você encontra assuntos relacionados a comportamento, saúde, educação e tudo mais que envolve  o desenvolvimento das crianças nesta faixa etária.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
#disqus: 'demowebsite'
email: 'd5a10.editora@gmail.com'
#mailchimp-list: 'https://gmail.us4.list-manage.com/subscribe/post?u=2e2de7e803c19c65957be170e&amp;id=436c8b7690'

### Basic localisation (l10n)
# If you customize the lang parameter, minima will try to use the strings in _data/locales/[lang].yml
# Read https://github.com/jekyll/minima/README.md for more information.
lang: pt

# Even the day and month names will be translated. You can customize your date by
# uncommenting the following line and customizing the date format:
date_format: "%b %-d, %Y"

include: ["_pages"]
permalink: /:title/

collections:
  dnli5:
    output: true
  pesquisa:
    output: true
  v:
    output: true

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    Parau:
      name:           Parahuari Branco (Parau)
      site:           https://www.linkedin.com/in/parau/
      avatar:         assets/images/parau.jfif
      bio:            "Pai, educador e desenvolvedor. Apaixonado pela área de educação, tenho mais de 20 anos de experiência no desenvolvimento de soluções tecnológicas voltadas a aprendizagem. Aqui, escrevo sobre o mundo digital e o relacionamento saudável entre a criança e a tecnologia."
      email:          d5a10.editora@gmail.com
      twitter:        https://twitter.com/parau

    Naira:
      name:           Naira Passoni
      site:           https://www.linkedin.com/in/naira-passoni-6756bb101/
      avatar:         assets/images/naira.jfif
      bio:            "Mãe, jornalista, autora, produtora de conteúdo... Em busca de respostas para as dúvidas da maternidade e da vida profissional. Aqui, quero dividir com outras pessoas as experiências e expectativas dessa jornada incrível e complexa! 😉"
      email:          naira.aprender.digital@gmail.com
      twitter:        https://twitter.com/NairaPassoni

    Nanra:
      name:           Nanra Branco
      site:           https://www.facebook.com/amodabrasilgastronomia/
      avatar:         assets/images/nanra.jpg
      bio:            "Jornalista apaixonada por gastronomia que transformou seu amor em profissão. Trabalho como personal chef, ministro cursos e palestras na área. Produtora de conteúdo do @amodabrasilgastronomia perfil do Instagram e Facebook sobre gastronomia e cozinha artesanal. Adepta da cozinha intuitiva, aqui quero compartilhar a importância da comida de verdade no dia a dia das famílias e do poder de descascar mais e desembalar menos."
      email:          amodabrasilgastronomia@gmail.com
      instagram:      https://www.instagram.com/amodabrasilgastronomia/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Naira
      avatar: /assets/images/naira.jfif
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]